### PR TITLE
.Net's BigInteger Migration for PaillerExt

### PR DESCRIPTION
**Pull request by Nicholas-Chew**

### CODE REVIEW

**Comment by Nicholas-Chew** [comment]
May I know what did I did wrong? I have checked three times and cant find the source of the issue.

**Comment by bazzilic** [comment]
You didn't update `nuget.config`

**Comment by bazzilic** [comment]
Also,
1) Untrack the `.vs` folder
2) Why did you delete `AssemblyInfo.cs`?

**Comment by bazzilic** [comment]
Alright.

Now, please, close this PR, squash your commits (see how [here](https://www.devroom.io/2011/07/05/git-squash-your-latests-commits-into-one/)), and make a PR against the `ENH-MigratingToNumerics` branch.

**Pull request closed without merging**
